import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import os
from dotenv import load_dotenv

load_dotenv()

SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_PORT = int(os.getenv("SMTP_PORT", "587"))
SMTP_USERNAME = os.getenv("SMTP_USERNAME")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD")
EMAIL_FROM = os.getenv("EMAIL_FROM")

def send_invoice_email(customer_email: str, invoice_data: dict):
    """
    Sends an HTML formatted invoice email to the customer.
    """
    if not all([SMTP_HOST, SMTP_USERNAME, SMTP_PASSWORD, EMAIL_FROM]):
        print("Email Configuration missing. Skipping email send.")
        return

    subject = f"Your Invoice from Billing System - #{invoice_data.get('id', 'N/A')}"
    
    # Create HTML content
    items_html = ""
    for item in invoice_data['items']:
        items_html += f"""
        <tr>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">{item['product_name']}</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee;">{item['quantity']}</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; text-align: right;">₹{item['unit_price']:.2f}</td>
            <td style="padding: 8px; border-bottom: 1px solid #eee; text-align: right;">₹{item['total_price']:.2f}</td>
        </tr>
        """

    html_content = f"""
    <html>
    <body style="font-family: Arial, sans-serif; color: #333; line-height: 1.6;">
        <div style="max-width: 600px; margin: 0 auto; border: 1px solid #ddd; padding: 20px; border-radius: 10px;">
            <h2 style="color: #2563eb; text-align: center;">Invoice Details</h2>
            <p>Hello,</p>
            <p>Thank you for your purchase. Here is your invoice summary:</p>
            
            <table style="width: 100%; border-collapse: collapse; margin: 20px 0;">
                <thead>
                    <tr style="background: #f8fafc;">
                        <th style="padding: 10px; text-align: left; border-bottom: 2px solid #ddd;">Product</th>
                        <th style="padding: 10px; text-align: left; border-bottom: 2px solid #ddd;">Qty</th>
                        <th style="padding: 10px; text-align: right; border-bottom: 2px solid #ddd;">Price</th>
                        <th style="padding: 10px; text-align: right; border-bottom: 2px solid #ddd;">Total</th>
                    </tr>
                </thead>
                <tbody>
                    {items_html}
                </tbody>
            </table>
            
            <div style="text-align: right; margin-top: 20px;">
                <p><strong>Total Without Tax:</strong> ₹{invoice_data['total_without_tax']:.2f}</p>
                <p><strong>Total Tax:</strong> ₹{invoice_data['total_tax']:.2f}</p>
                <p style="font-size: 1.2rem; color: #1e293b;"><strong>Net Amount Paid: ₹{invoice_data['rounded_net_price']:.2f}</strong></p>
            </div>
            
            <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; font-size: 0.8rem; color: #777; text-align: center;">
                <p>This is an automated bill generated by Billing System.</p>
            </div>
        </div>
    </body>
    </html>
    """

    msg = MIMEMultipart()
    msg['From'] = EMAIL_FROM
    msg['To'] = customer_email
    msg['Subject'] = subject
    
    msg.attach(MIMEText(html_content, 'html'))

    try:
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USERNAME, SMTP_PASSWORD)
            server.send_message(msg)
            print(f"Invoice email sent successfully to {customer_email}")
    except Exception as e:
        print(f"Error sending email: {e}")
